USE WebStor;
GO

SELECT [EMPL_NUM], [NAME], [AGE], [TITLE] FROM [dbo].[SALESREPS]
WHERE AGE > 45
ORDER BY AGE DESC;
GO


SELECT DISTINCT [MFR], [PRODUCT] FROM [dbo].[ORDERS] 
WHERE [ORDER_DATE] BETWEEN '2008-01-01'AND '2009-01-01';
GO


SELECT TOP 1 WITH TIES [REP], COUNT(DISTINCT ORDER_NUM) AS QUANTITY 
FROM [dbo].[ORDERS]
WHERE [ORDER_DATE] BETWEEN '2008-01-01'AND '2009-01-01'
GROUP BY REP
ORDER BY COUNT(DISTINCT ORDER_NUM) DESC;
GO