USE [WebStor]

GO
CREATE SCHEMA KAZAK
GO

CREATE TABLE KAZAK.DATATYPES
ID BIGINT
AGE TINYINT
);
INSERT INTO KAZAK.DATATYPES(ID, AGE)
VALUES(10000,34);
INSERT INTO KAZAK.DATATYPES(ID, AGE)
VALUES(10001,32);
INSERT INTO KAZAK.DATATYPES(ID, AGE)
VALUES(`10002`,`32`);
INSERT INTO KAZAK.DATATYPES(ID, AGE)
VALUES(`10003`,`35`);
INSERT INTO KAZAK.DATATYPES(ID, AGE)
VALUES(`19700101`,`35`);
INSERT INTO BOJKO.DATATYPES(ID, AGE)
VALUES(`1970-01-01`,`35`);

SELECT *
FROM KAZAK.DATATYPES;
