CREATE TABLE CUSTOMERS

(CUST_NUM INTEGER NOT NULL,

COMPANY VARCHAR(20) NOT NULL,

CUST_REP INTEGER,

CREDIT_LIMIT MONEY,

PRIMARY KEY (CUST_NUM),

CONSTRAINT HASREP FOREIGN KEY (CUST_REP)

REFERENCES SALESREPS

ON DELETE SET NULL)