CREATE TABLE PRODUCTS

(MFR_ID CHAR(3) NOT NULL,

PRODUCT_ID CHAR(5) NOT NULL,

DESCRIPTION VARCHAR(20) NOT NULL,

PRICE MONEY NOT NULL,

QTY_ON_HAND INTEGER NOT NULL,

PRIMARY KEY (MFR_ID, PRODUCT_ID))