USE [WebStor];

GO
CREATE SCHEMA DUKHOVENKOKA; 
GO

CREATE TABLE DUKHOVENKOKA.DATATYPES (

ID BIGINT,

AGE TINYINT

);

INSERT INTO DUKHOVENKOKA.DATATYPES(ID, AGE)

VALUES(10000, 34);

INSERT INTO DUKHOVENKOKA.DATATYPES(ID, AGE)

VALUES(10001, 32);

-- Implicit data type conversion

INSERT INTO DUKHOVENKOKA.DATATYPES(ID, AGE)

VALUES('10002', 32);

-- Implicit data type conversion

INSERT INTO DUKHOVENKOKA.DATATYPES(ID, AGE)

VALUES('10003', '35');

-- Implicit data type conversion

INSERT INTO DUKHOVENKOKA.DATATYPES(ID, AGE)

VALUES('19700101', '35');

-- Implicit data type conversion IS NOT WORKING!

INSERT INTO DUKHOVENKOKA.DATATYPES(ID, AGE)

VALUES('19700102', '35');

SELECT *
FROM DUKHOVENKOKA.DATATYPES;
