USE WebStor1;
GO
 
--Завдання 1
SELECT [EMPL_NUM], [NAME], [AGE], [TITLE] FROM [dbo].[SALESREPS]
WHERE AGE > 45
ORDER BY AGE DESC;
GO

--Завдання 2
SELECT DISTINCT [MFR], [PRODUCT] FROM [dbo].[ORDERS]
WHERE [ORDER_DATE] BETWEEN '20080101' AND '20081231';
GO

--Завдання 3
SELECT TOP 1 WITH TIES [REP], COUNT (DISTINCT[ORDER_NUM]) AS Quantity
FROM [dbo].[ORDERS] WHERE [ORDER_DATE] BETWEEN '20080101' AND '20081231'
GROUP BY REP
ORDER BY COUNT (DISTINCT[ORDER_NUM]) DESC;
GO