USE WebStor
GO

CREATE SCHEMA DANYLCHENKO;
GO
CREATE TABLE DANYLCHENKO.DATATYPES 
(ID BIGINT,
AGE TINYINT)

INSERT INTO DANYLCHENKO.DATATYPES(ID, AGE)
VALUES(10000, 34);

INSERT INTO DANYLCHENKO.DATATYPES(ID, AGE)
VALUES(10001, 32);

INSERT INTO DANYLCHENKO.DATATYPES(ID, AGE)
VALUES('10002', 32);

INSERT INTO DANYLCHENKO.DATATYPES(ID, AGE)
VALUES('10003', '35');

INSERT INTO DANYLCHENKO.DATATYPES(ID, AGE)
VALUES('19700101', '35');

INSERT INTO DANYLCHENKO.DATATYPES(ID, AGE)
VALUES('19700101', '35');

SELECT * 
  FROM DANYLCHENKO.DATATYPES

