USE WebStor;
GO

--Завдання 1
SELECT DISTINCT o.[MFR]
FROM [dbo].[CUSTOMERS] c
INNER JOIN [dbo].[ORDERS] o ON c.[CUST_REP] = o.[REP]
WHERE o.[ORDER_DATE] BETWEEN '2008-01-01' AND '2009-01-01'
AND c.[COMPANY] LIKE '%CORP%';
GO

--Завдання 2
SELECT c.[CUST_NUM], MONTH(o.[ORDER_DATE]) AS МІСЯЦЬ_ЗАМОВЛЕННЯ,COUNT(DISTINCT o.[ORDER_NUM]) AS КІЛЬКІСТЬ_УНІКАЛЬНИХ_ЗАМОВЛЕНЬ
FROM [dbo].[CUSTOMERS] c
LEFT OUTER JOIN [dbo].[ORDERS] o ON c.[CUST_NUM] = o.[CUST]
WHERE o.[ORDER_DATE] BETWEEN '2008-01-01' AND '2009-01-01'
AND c.[COMPANY] LIKE '%CORP%'
GROUP BY c.[CUST_NUM], MONTH(o.[ORDER_DATE])
ORDER BY КІЛЬКІСТЬ_УНІКАЛЬНИХ_ЗАМОВЛЕНЬ DESC;
GO

--Завдання 3
SELECT DISTINCT c.[CUST_NUM], UPPER(c.[COMPANY]) AS НАЗВА_КОМПАНІЇ, p.[DESCRIPTION]
FROM [dbo].[CUSTOMERS] c
LEFT OUTER JOIN [dbo].[ORDERS] o ON c.[CUST_NUM] = o.[CUST]
LEFT OUTER JOIN [dbo].[PRODUCTS] p ON p.[PRODUCT_ID] = o.[PRODUCT]
WHERE o.[ORDER_DATE] BETWEEN '2008-01-01' AND '2009-01-01'
AND c.[COMPANY] LIKE '%CORP%';
GO