USE [WebStor1];

GO
CREATE SCHEMA ZHURAVEL;
CREATE TABLE ZHURAVEL.DATATYPES (
       ID  BIGINT, 
	   AGE TINYINT 
);

INSERT INTO ZHURAVEL.DATATYPES(ID, AGE)
VALUES(10000, 34);

INSERT INTO ZHURAVEL.DATATYPES(ID, AGE)
VALUES(10001, 32);


INSERT INTO .DATATYPES(ID, AGE)
VALUES('10002', 32);


INSERT INTO ZHURAVEL.DATATYPES(ID, AGE)
VALUES('10003', '35');


INSERT INTO ZHURAVEL.DATATYPES(ID, AGE)
VALUES('19700101', '35');


INSERT INTO ZHURAVEL.DATATYPES(ID, AGE)
VALUES('1970-01-01', '35');

SELECT * 
  FROM ZHURAVEL.DATATYPES;
