USE [WebStor]
GO

CREATE SCHEMA VOVCHOK; --Власне прізвище
GO

CREATE TABLE VOVCHOK.DATATYPES (
ID BIGINT, -- Unique identifier of an entity 
AGE TINYINT -- Number of years
);


INSERT INTO VOVCHOK.DATATYPES(ID, AGE)
VALUES(10000, 34);
INSERT INTO VOVCHOK.DATATYPES(ID, AGE)
VALUES(10001, 32);
INSERT INTO VOVCHOK.DATATYPES(ID, AGE)
VALUES(10002, 32);
INSERT INTO VOVCHOK.DATATYPES(ID, AGE)
VALUES(10003, 35);
INSERT INTO VOVCHOK.DATATYPES(ID, AGE)
VALUES(19700101, 35);
INSERT INTO VOVCHOK.DATATYPES(ID, AGE)
VALUES(1970-01-01, 35);


SELECT *
FROM VOVCHOK.DATATYPES;