GO
CREATE SCHEMA DUKHOVENKOKA; 
GO

CREATE TABLE ZHUK.DATATYPES (

ID BIGINT,

AGE TINYINT

);
INSERT INTO ZHUK.DATATYPES(ID, AGE)

VALUES(10000, 34);

INSERT INTO ZHUK.DATATYPES(ID, AGE)

VALUES(10001, 32);

-- Implicit data type conversion

INSERT INTO ZHUK.DATATYPES(ID, AGE)

VALUES('10002', 32);

-- Implicit data type conversion

INSERT INTO ZHUK.DATATYPES(ID, AGE)

VALUES('10003', '35');

-- Implicit data type conversion

INSERT INTO ZHUK.DATATYPES(ID, AGE)

VALUES('19700101', '35');

-- Implicit data type conversion IS NOT WORKING!

INSERT INTO ZHUK.DATATYPES(ID, AGE)

VALUES('19700102', '35');

SELECT *
FROM ZHUK.DATATYPES;