CREATE DATABASE Simple;




USE Simple

GO
CREATE SCHEMA HOLOVKO;

GO

CREATE TABLE HOLOVKO.DATATYPES (
       ID  BIGINT, 
	   AGE TINYINT);

	   INSERT INTO HOLOVKO.DATATYPES(ID, AGE)
VALUES(10000, 34);

INSERT INTO HOLOVKO.DATATYPES(ID, AGE)
VALUES(10001, 32);


INSERT INTO HOLOVKO.DATATYPES(ID, AGE)
VALUES('10002', 32);


INSERT INTO HOLOVKO.DATATYPES(ID, AGE)
VALUES('10003', '35');

INSERT INTO HOLOVKO.DATATYPES(ID, AGE)
VALUES('19700101', '35');

INSERT INTO HOLOVKO.DATATYPES(ID, AGE)
VALUES('1970-01-01', '35');


SELECT * 
  FROM HOLOVKO.DATATYPES;