use WebStor;
go


select DISTINCT [MFR] from ORDERS INNER JOIN CUSTOMERS on CUSTOMERS.[CUST_NUM] = ORDERS.[CUST]  
WHERE ORDERS.ORDER_DATE BETWEEN '20080101' AND '20081231' AND CUSTOMERS.[COMPANY] LIKE '%CORP%';
go


SELECT CUST_NUM, MONTH(ORDER_DATE) AS OrderMonth, COUNT(DISTINCT ORDER_NUM) AS UniqueOrdersCount
FROM CUSTOMERS LEFT OUTER JOIN ORDERS ON CUST_NUM = CUST
WHERE [ORDER_DATE] BETWEEN '2008-01-01' AND '2009-01-01'
AND COMPANY LIKE '%CORP%' GROUP BY CUST_NUM, MONTH(ORDER_DATE)
ORDER BY UniqueOrdersCount DESC;
go

SELECT distinct [CUST_NUM], [PRODUCT_ID]  from CUSTOMERS 
LEFT OUTER JOIN [ORDERS] on [ORDERS].CUST= CUSTOMERS.CUST_NUM
LEFT OUTER JOIN PRODUCTS on [ORDERS].PRODUCT = PRODUCTS.PRODUCT_ID
WHERE [ORDER_DATE] BETWEEN '2008-01-01' AND '2009-01-01'
AND COMPANY LIKE '%CORP%'
go