use WebStor

Select EMPL_NUM, NAME, AGE, TITLE from SALESREPS
	WHERE AGE > 45 ORDER BY AGE DESC;

SELECT DISTINCT [MFR], [PRODUCT] FROM ORDERS WHERE ORDER_DATE BETWEEN '20080101' AND '20081231';

SELECT TOP(1) WITH TIES REP, COUNT(*) as TotalCount
from ORDERS WHERE [ORDER_DATE] between '20080101' and '20081231'
GROUP BY REP
ORDER BY TotalCount DESC;