USE WebStor
Go


--- Завдання 1 
SELECT [EMPL_NUM], [NAME], [AGE], [TITLE]
FROM [dbo].[SALESREPS]
    WHERE AGE > 45
    ORDER BY AGE DESC;
Go


--- Завдання 2
SELECT DISTINCT [MFR], [PRODUCT]
FROM [dbo].[ORDERS]
   WHERE [ORDER_DATE] BETWEEN '2008-01-01' AND '2008-12-31';
GO

--- Завдання 3
SELECT  TOP 1 WITH TIES [REP], COUNT (DISTINCT [ORDER_NUM]) AS Quantity
FROM [dbo].[ORDERS]
   WHERE [ORDER_DATE] BETWEEN '2008-01-01' AND '2008-12-31'
   GROUP BY REP
   ORDER BY COUNT (DISTINCT [ORDER_NUM]) DESC;
GO
